Repository danielgtaylor/python-betterproto, pull requests merged in 2020-05, with the labels that each got.

#46 Improve performance of serialize/deserialize by caching type information of fields in class
  betterproto/__init__.py
  betterproto/tests/test_inputs.py
  conftest.py
Labels: enhancement

#40 Support using Google's wrapper types as RPC output values
  betterproto/plugin.py
  betterproto/tests/inputs/googletypes_response/googletypes_response.proto
  betterproto/tests/inputs/googletypes_response/test_googletypes_response.py
  betterproto/tests/inputs/googletypes_response_embedded/googletypes_response_embedded.proto
  betterproto/tests/inputs/googletypes_response_embedded/test_googletypes_response_embedded.py
  betterproto/tests/mocks.py
  betterproto/tests/test_inputs.py
Labels: enhancement

#71 Release 1.2.4
  CHANGELOG.md
  setup.py
Labels: documentation

#69 Bugreports
  betterproto/tests/README.md
  betterproto/tests/generate.py
  betterproto/tests/inputs/casing_message_field_uppercase/casing_message_field_uppercase.json
  betterproto/tests/inputs/casing_message_field_uppercase/casing_message_field_uppercase.proto
  betterproto/tests/inputs/casing_message_field_uppercase/casing_message_field_uppercase.py
  betterproto/tests/inputs/config.py
  betterproto/tests/inputs/googletypes_service_returns_empty/googletypes_service_returns_empty.proto
  betterproto/tests/inputs/import_packages_same_name/import_packages_same_name.proto
  betterproto/tests/inputs/import_packages_same_name/posts_v1.proto
  betterproto/tests/inputs/import_packages_same_name/users_v1.proto
  betterproto/tests/inputs/import_service_input_message/import_service_input_message.proto
  betterproto/tests/inputs/import_service_input_message/request_message.proto
  betterproto/tests/inputs/import_service_input_message/test_import_service.py
  betterproto/tests/inputs/keywords/keywords.json
  betterproto/tests/inputs/keywords/keywords.proto
  betterproto/tests/inputs/namespace_builtin_types/namespace_builtin_types.json
  betterproto/tests/inputs/namespace_builtin_types/namespace_builtin_types.proto
  betterproto/tests/inputs/namespace_keywords/namespace_keywords.json
  betterproto/tests/inputs/namespace_keywords/namespace_keywords.proto
  betterproto/tests/inputs/xfail.py
  betterproto/tests/test_inputs.py
  betterproto/tests/util.py
Labels: documentation, has test

#62 Cache field metadata, to avoid calling `dataclasses.fields` to get more than 10% performance improvement
  betterproto/__init__.py
Labels: enhancement
