Repository danielgtaylor/python-betterproto, pull requests merged in 2023-10, with the labels that each got.

#293 Map enum int's into Enums redux
  poetry.lock
  pyproject.toml
  src/betterproto/__init__.py
  src/betterproto/enum.py
  tests/inputs/enum/test_enum.py
  tests/test_enum.py
Labels: high priority

#535 Implementing pickle methods
  poetry.lock
  pyproject.toml
  src/betterproto/__init__.py
  tests/test_features.py
  tests/test_pickling.py
Labels: enhancement

#187 Remove enum prefixes
  src/betterproto/casing.py
  src/betterproto/compile/naming.py
  src/betterproto/enum.py
  src/betterproto/plugin/models.py
  tests/inputs/enum/enum.proto
  tests/inputs/enum/test_enum.py
Labels: enhancement, high priority
